name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        cc: [/usr/bin/gcc, /usr/bin/clang]

    env:
      CC: ${{ matrix.cc }}

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Build with make
      run: make all tests

    - name: Build with cmake
      run: |
        mkdir build
        cd build
        cmake ..
        make
